# Generated by Django 3.0.2 on 2020-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_features'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingfeature',
            name='feature',
        ),
        migrations.AddField(
            model_name='bookingfeature',
            name='feature',
            field=models.ManyToManyField(to='setting.Features'),
        ),
    ]
