# Generated by Django 3.0.2 on 2020-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200210_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_geocode',
            field=models.DecimalField(decimal_places=8, default=6, max_digits=10, verbose_name='Destination Cordinate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='origin_geocode',
            field=models.DecimalField(decimal_places=8, default=2, max_digits=11, verbose_name='Origin Cordinate'),
            preserve_default=False,
        ),
    ]
